name: 'Checkout Platform Settings'
description: 'Checkout Platform Settings'

inputs:
  settingsPath:
    description: 'The path to the CARML settings JSON file'
    required: true

outputs:
  # Feature Flags
  featureFlags:
    value: ${{ steps.get-feature-flags.outputs.featureFlags }}

runs:
  using: 'composite'
  steps:
    - name: 'Get Feature Flags'
      id: get-feature-flags
      shell: pwsh
      run: |

        # Load Settings File
        $Settings = Get-Content -Path ${{ inputs.settingsPath }} | ConvertFrom-Json -AsHashTable

        # Get Feature Flags
        $FeatureFlags = $Settings.featureFlags
        $FeatureFlagsKeys = $FeatureFlags.Keys
        Write-Verbose $Settings.featureFlags -Verbose
        foreach($Key in $Settings.featureFlags.Keys){
          $FeatureFlagState = $Settings.featureFlags[$Key].ToString().ToLower()
          Write-Verbose "Feature ==> $Key = $FeatureFlagState" -Verbose
          Write-Output "::set-output name=$Key::$FeatureFlagState"
        }

        # Get Feature Flags (JSON)
        $featuresFlagsJSON = $FeatureFlags | ConvertTo-Json -Compress
        Write-Output "::set-output name=featureFlags::$featuresFlagsJSON"

