name: 'Set Environment Variables'
description: 'Set Environment Variables'

inputs:
  variablesPath:
    description: 'The path to the variables YAML file'
    required: true

outputs:
  # Environment Variables
  environmentVariables:
    description: 'Environment Variables'
    value: ${{ steps.set-env-variables.outputs.environmentVariables }}

runs:
  using: 'composite'
  steps:
    - name: 'Get and Combine Environment Variables'
      id: set-env-variables
      shell: pwsh
      run: |

        # Load Variables File (YAML)
        $VariablesYAML = Get-Content -Path ${{ inputs.variablesPath }}

        # Extract Environment Variables (using powershell-yaml)
        $KeyValuePair = $VariablesYAML | ConvertFrom-Yaml | Select-Object -ExpandProperty variables

        # Process key value pairs as environment variables
        foreach ($Key in $KeyValuePair.Keys.split(' ')) {
          Write-Verbose "$Key=$($KeyValuePair[$Key])" -Verbose
          # Set Environment Variables
          Write-Output "$Key=$($KeyValuePair[$Key])" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        }

