name: 'Set Environment Variables'
description: 'Set Environment Variables'

inputs:
  settingsPath:
    description: 'The path to the platform settings JSON file'
    required: true

outputs:
  # Environment Variables
  environmentVariables:
    description: 'Environment Variables'
    value: ${{ steps.set-env-variables.outputs.environmentVariables }}

runs:
  using: 'composite'
  steps:
    - name: 'Get and Combine Environment Variables'
      id: set-env-variables
      shell: pwsh
      run: |

        # Load Settings File
        $Settings = Get-Content -Path ${{ inputs.settingsPath }} | ConvertFrom-Json -AsHashTable

        # Extract Environment Variables
        $Shared_EnvironmentVariables = $Settings.pipelines.shared.variables
        $GitHub_EnvironmentVariables = $Settings.pipelines.githubActions.variables

        # Process key value pairs as environment variables
        $KeyValuePair = $Shared_EnvironmentVariables + $GitHub_EnvironmentVariables
        foreach ($Key in $KeyValuePair.Keys.split(' ')) {
          Write-Verbose "$Key=$($KeyValuePair[$Key])" -Verbose
          # Set Environment Variables
          Write-Output "$Key=$($KeyValuePair[$Key])" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        }

